source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.0'

# Use mysql as the database for Active Record
gem 'mysql2'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
 gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'jquery-ui-rails', '4.0.5', path: 'vendor/plugins/jquery-ui-rails-4.0.5'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
gem 'roo'	#gema para excel

gem 'actionpack-action_caching'

gem 'devise', '3.0.0.rc'
gem "twitter-bootstrap-rails", '2.2.8', path: 'vendor/plugins/twitter-bootstrap-rails-2.2.8'
#gem "therubyracer"
gem "less-rails" #Sprockets (what Rails 3.1 uses for its asset pipeline) supports LESS
gem "haml-rails"
gem 'quiet_assets', :group => :development
gem 'simple_form'
gem 'jquery-validation-rails'
gem 'soap4r'
gem 'savon'
gem 'json' 
gem 'state_machine'

gem 'thin'

gem "raphael-rails"

gem 'unicorn'
#gem 'pg'

#Gem paperclip
gem 'paperclip', '~> 3.0'

gem 'prawn'
gem "prawnto_2", :require => "prawnto"

gem 'activerecord-import'


# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

gem 'dbi'

gem 'dbd-odbc'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
