class AddWorkersToWorker < ActiveRecord::Migration
  def change
    add_column :workers,:cv, :string
    add_column :workers,:cv_file_name, :string
    add_column :workers,:cv_content_type, :string
    add_column :workers,:cv_file_size, :integer
    add_column :workers,:cv_updated_at, :datetime
    add_column :workers,:antecedent_police, :string
    add_column :workers,:antecedent_police_file_name, :string
    add_column :workers,:antecedent_police_content_type, :string
    add_column :workers,:antecedent_police_file_size, :integer
    add_column :workers,:antecedent_police_updated_at, :datetime
    add_column :workers,:dni, :string
    add_column :workers,:dni_file_name, :string
    add_column :workers,:dni_content_type, :string
    add_column :workers,:dni_file_size, :integer
    add_column :workers,:dni_updated_at, :datetime
    add_column :workers,:cts_deposit_letter, :string
    add_column :workers,:cts_deposit_letter_file_name, :string
    add_column :workers,:cts_deposit_letter_content_type, :string
    add_column :workers,:cts_deposit_letter_file_size, :integer
    add_column :workers,:cts_deposit_letter_updated_at, :datetime
    add_column :workers,:pension_funds_letter, :string
    add_column :workers,:pension_funds_letter_file_name, :string
    add_column :workers,:pension_funds_letter_content_type, :string
    add_column :workers,:pension_funds_letter_file_size, :integer
    add_column :workers,:pension_funds_letter_updated_at, :datetime
    add_column :workers,:affidavit, :string
    add_column :workers,:affidavit_file_name, :string
    add_column :workers,:affidavit_content_type, :string
    add_column :workers,:affidavit_file_size, :integer
    add_column :workers,:affidavit_updated_at, :datetime
    add_column :workers,:marriage_certificate, :string
    add_column :workers,:marriage_certificate_file_name, :string
    add_column :workers,:marriage_certificate_content_type, :string
    add_column :workers,:marriage_certificate_file_size, :integer
    add_column :workers,:marriage_certificate_updated_at, :datetime
    add_column :workers,:birth_certificate_of_childer, :string
    add_column :workers,:birth_certificate_of_childer_file_name, :string
    add_column :workers,:birth_certificate_of_childer_content_type, :string
    add_column :workers,:birth_certificate_of_childer_file_size, :integer
    add_column :workers,:birth_certificate_of_childer_updated_at, :datetime
    add_column :workers,:dni_wife_kids, :string
    add_column :workers,:dni_wife_kids_file_name, :string
    add_column :workers,:dni_wife_kids_content_type, :string
    add_column :workers,:dni_wife_kids_file_size, :integer
    add_column :workers,:dni_wife_kids_updated_at, :datetime
    add_column :workers,:schoolar_certificate, :string
    add_column :workers,:schoolar_certificate_file_name, :string
    add_column :workers,:schoolar_certificate_content_type, :string
    add_column :workers,:schoolar_certificate_file_size, :integer
    add_column :workers,:schoolar_certificate_updated_at, :datetime
  end
end
